### ISSUE TITLE
Another Example of Kitchen-Docker and Travis CI

### ISSUE THREAD

**Issue by ghost** [zuazo/kitchen-in-travis-native#3]
Hey Guys,

I just wanted to share another example of how I have been using this just incase anyone is interested.  

``` yaml
language: ruby

sudo: required

services:
  - docker

# attempt to speed up build by installing Gecode 3.7.3 from Ubuntu 12.04
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libqt4-dev libqtcore4 libqtgui4 libboost-dev
  - curl -O http://lug.mtu.edu/ubuntu/pool/universe/g/gecode/libgecode-dev_3.7.1-3_amd64.deb
  - curl -O http://lug.mtu.edu/ubuntu/pool/universe/g/gecode/libgecode-doc_3.7.1-3_all.deb
  - curl -O http://lug.mtu.edu/ubuntu/pool/universe/g/gecode/libgecode30_3.7.1-3_amd64.deb
  - curl -O http://lug.mtu.edu/ubuntu/pool/universe/g/gecode/libgecodeflatzinc30_3.7.1-3_amd64.deb
  - curl -O http://lug.mtu.edu/ubuntu/pool/universe/g/gecode/libgecodegist30_3.7.1-3_amd64.deb

install:
  - sudo dpkg -i *.deb
  - bundle install

script:
  - bundle exec rake style
  - bundle exec rake unit
  - bundle exec kitchen test -d never

env:
  global:
    - USE_SYSTEM_GECODE=1
    - KITCHEN_YAML=.kitchen.docker.yml
```
